module.exports = {
    products : [
        {
            dressId: '1',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/image1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStocks: 8,
        },
        {
            dressId: '2',
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/image1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStocks: 8,
        },
        {
            dressId: '3',
            name: 'Best Shirt',
            category: 'Shirts',
            image: '/images/image1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStocks: 0,
        },
        {
            dressId: '4',
            name: 'Slim Pants',
            category: 'Shirts',
            image: '/images/image1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStocks: 10,
        },
        {
            dressId: '5',
            name: 'Fit Pants',
            category: 'Shirts',
            image: '/images/image1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStocks: 8,
        },
        {
            dressId: '6',
            name: 'Best Pants',
            category: 'Shirts',
            image: '/images/image1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStocks: 8,
        }
    ]
}